### ISSUE TITLE
Is this appropriate for MDAnalysis?

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/beckernels#1]
@dotsdl – should this be here or under Becksteinlab?

**Comment by dotsdl** [comment]
Ooops! Yeah, that was a complete mistake. I could have sworn I switched to the right org, but apparently not. :/

**Comment by dotsdl** [comment]
Sorry everyone for automatically subscribing you, too. I should slow down and lay off the caffeine.

**Comment by orbeckst** [comment]
hehe

On 15 Dec, 2015, at 17:34, David Dotson wrote:

> Sorry everyone for automatically subscribing you, too. I should slow down and lay off the caffeine.
> 
> �
> Reply to this email directly or view it on GitHub.

## 

Oliver Beckstein \* orbeckst@gmx.net
skype: orbeckst  \* orbeckst@gmail.com
